version: '3'
services:
  application:
    image: finleap/study-case
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - redis
  #  deploy:
  #    restart_policy:
  #      condition: on-failure
  #      delay: 5s
  #      window: 120s

  redis:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - backend
    entrypoint: redis-server --protected-mode no
  #  deploy:
  #    replicas: 1
  #    update_config:
  #      parallelism: 1
  #      delay: 10s
  #    restart_policy:
  #     condition: on-failure


networks:
  backend:
